### ISSUE TITLE
Sysfiles1 missing

### ISSUE THREAD

**Issue by franzt** [BunsenLabs/bunsen-netinstall#1]
In one of the last commits the folder above was removed. this leads to errors while Runign the script, unless the singel file is added.

**Comment by johnraff** [comment]
Thank you franzt. The file that was there is no longer necessary, but the script needs amending so that it does not return an error.

**EDIT:** in fact the problem was that git ignores empty directories. Adding a .gitignore empty file should fix it.

**Comment by smacz42** [comment]
@johnraff I am still recieving the following error:

```
gen_sources: line 1: sysfiles1/etc/apt/sources.list: No such file or directory
####### ERROR ########
There was a problem editing sources.list.
```

This was after a retrieval and run of the `master.tar.gz` tarball with the `.gitignore` file included in `~/bunsen-netinstall-master/sysfiles1` directory last night.

Adding the `sources.list` file where the script seems to be looking for it was the only way that the script was able to continue.

**Comment by franzt** [comment]
The esiest Solution for me was to create the file 
/bunsen-netinstall-master/sysfiles1/etc/apt/apt.conf.d/90bunsen 
and put the line

APT::InstallRecommends "true";

into it

**Comment by DrKondor** [comment]
I will personally confirm that franzt's fix works to get the installer going. Thanks franzt! 

Everything seems to have installed -- however, after reboot, the default login screen doesn't recognize my user/pass. 

I can log in fine by switching to another tty console (Ctrl-Alt-F1 for example.) But no graphical desktop.

**Comment by franzt** [comment]
that is just a hack to have a file were no file is  neede. I'll try to fix it properly wen i get the time

**Comment by johnraff** [comment]
90bunsen was removed from the installer script because it is now installed by **bunsen-configs**.
However, removing its directory, I forgot the script would still need to write a sources.list file in etc/apt.

sysfiles1/etc/apt has now been restored and I'm hoping the script will work again without any other changes.

**Comment by johnraff** [comment]
@DrKondor if your login problem persists with the current script, would you mind starting a new issue on that topic?

**Comment by johnraff** [comment]
The lightdm login issue was due to bunsen-utilities being missing from the build list.
I believe both these issues have now been fixed - feel free to reopen this if they recur.
