### ISSUE TITLE
jessie net-inst plus repository packages messed up

### ISSUE THREAD

**Issue by lustremedia** [BunsenLabs/bunsen-netinstall#10]
Hi  I installed a fresh net-inst 8.3 jessie base system, then used the repository method to get bunsen on the machine. However I do not see any tabs neither is there any sign of conky or terminator, just a blank desktop image. right click menu works but there are also only a view items on there, and no browser (error when trying to open) I must add that I have not installed any meta packages. Is this normal?

The system seems to be crippled. 

Would you recomend to use this script to maybe ease the pain?

**Comment by johnraff** [comment]
Hi lustremedia,
at present there are no BunsenLabs metapackages, and it looks as if you are missing the default set of needed packages.

If all you have done so far is to install a Debian Jessie netinstall and add the BunsenLabs packages then, yes, the netinstall script is one option. I would suggest perhaps first _removing_ the BL packages you have installed so far and removing the BL repository entries you have added, get back to a "clean" netinstall and run the script from there.

Alternatively, the two files _pkgs-norecs_ and _pkgs-recs_ contain a list of what you need - you could just install them manually on your current system and reboot.

**Comment by lustremedia** [comment]
Thanks for the answer John. I ran the netinstall script after removing all packages but it failed utterly and did not give me a virtuous netinstall. Thus I went through a new install then used the netinstall script and then the system came up nice and crisp. Works great and I am writing from the bunsen as of now, and I love it!

**Comment by johnraff** [comment]
Glad it worked out for you!
