### ISSUE TITLE
Failed to start LightDM after reboot on Helium-Dev branch

### ISSUE THREAD

**Issue by kafran** [BunsenLabs/bunsen-netinstall#16]
It failed to start LightDM after the reboot on Helium-Dev branch. I couldn't startx either.

**Comment by kafran** [comment]
Problem solved after installing `xserver-xorg-video-intel`.

**Comment by johnraff** [comment]
@kafran thank you for raising this.
In Debian Jessie, *xserver-xorg-video-intel* is an indirect dependency of *xorg*, which is on our install list. 
( xorg > xserver-xorg > xserver-xorg-video-all > xserver-xorg-video-intel ) 

However in Debian Stretch *xserver-xorg-video-intel* is only a *recommendation* of *xserver-xorg-video-all*, so will not be installed by the netinstall script. The [package](https://packages.debian.org/stretch/xserver-xorg-video-intel) now says:
>The use of this driver is discouraged if your hw is new enough (ca. 2007 and newer). You can try uninstalling this driver and let the server use it's builtin modesetting driver instead.

Clearly that didn't work in your case, and we now have to think about whether to include this package by default or not.

**Comment by Head-on-a-Stick** [comment]
The Intel DDX driver is not needed to start the X server.

@kafran, can you please post the full output of:

`lspci -knn | grep -iA2 'vga\|3d'`

**Comment by kafran** [comment]
Ok guys. Happy to help.

First:
> Please also explain how exactly you installed your "Helium-Dev" system.

I did a fresh install with Debian Stretch netinstall.iso; Followed up the installation instruction about package selection (standard system utilities, only) and on the first boot Downloaded the "Helium-Dev" branch and `./install`; Everything went fine.

When the system rebooted, it was not possible to start LightDM. Reading the Xorg.log I saw the problem was the intel driver missing so I installed it and everything was fine.

About the output of `lspci -knn | grep -iA2 'vga\|3d'`

```
kafran@1040BR:~$ lspci -knn | grep -iA2 'vga\|3d'
00:02.0 VGA compatible controller [0300]: Intel Corporation Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller [8086:a011]
	Subsystem: Hewlett-Packard Company Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller [103c:3660]
	Kernel driver in use: i915
```

**Comment by johnraff** [comment]
btw This issue is now also being discussed on the [BunsenLabs Forums](https://forums.bunsenlabs.org/viewtopic.php?id=3699).

**Comment by johnraff** [comment]
*xserver-xorg-video-intel* has been added to the package install list.
