### ISSUE TITLE
helium-dev: install fails due to xserver-xorg-input-vmmouse unavailable

### ISSUE THREAD

**Issue by capn-damo** [BunsenLabs/bunsen-netinstall#19]
`pkg-norecs` has `xserver-xorg-input-vmmouse`, which is not in any Debian repository, so the install fails. If it is commented out then the installation succeeds.

**Comment by johnraff** [comment]
Thank you. 
xserver-xorg-input-vmmouse is in Jessie but not Stretch. 
Now fixed in  f79f520.
