### ISSUE TITLE
bunsen-netinstall on Devuan

### ISSUE THREAD

**Issue by chicagoist** [BunsenLabs/bunsen-netinstall#22]
Need fix install script:

#trap 'giveup "Script terminated." 1' 1 2 3 15
#[[ $user = root ]] && giveup "This script should be run by a normal user, not root" 1

And use:

$ sudo ./install

**Comment by johnraff** [comment]
Sorry, BunsenLabs is intended to be installed on standard Debian.

Anyway, the install script should not be run as root, as the message says. Making that possible would mean re-checking all the code, which there isn't time for at the moment.

Please feel free to make your own adaptions to run it on Devuan.
