### ISSUE TITLE
almost works on Pinebook a64

### ISSUE THREAD

**Issue by sarnold** [BunsenLabs/bunsen-netinstall#24]
First, thanks!  It's nice to see openbox et al are still being used.  So I had to give this a try on a non-x86 target.

Other than the x86-only driver/firmware packages, I was only missing 2 important items:

* jgmenu - retrieved and built from debian bookworm sources on pinebook
* bunsen-blob - unresolved, no sources available

So all I really need is the last one; can you make the sources available?  Even better, could you add arm64 and armhf architectures to your deb package feed?

In this case I started with Debian bullseye installer images for pinebook, but the installer failed to install a bootloader so I ended up doing a manual install following the LinuxOnArm wiki process similar to this: https://forum.digikey.com/t/debian-getting-started-with-the-rock-pi-4/12973

I bring that ^^ up because of the debian rootfs tarballs and package repos maintained by the same digikey guy who wrote most of those linux guides: https://rcn-ee.com/rootfs/eewiki/minfs/

So anyone interested in trying this approach can take advantage of these resources.

**Comment by rbh-se** [comment]
Hi and Welcome to BunsenLabs.

Source for bunsen-blob, **is** available here: https://github.com/BunsenLabs/bunsen-blob.
Only for BL Boron/Debian bookworm.

Yes, full support for arm64 and armhf , would be nice, but is not doable at the moment.
