### ISSUE TITLE
modified system files?

### ISSUE THREAD

**Issue by brontosaurusrex** [BunsenLabs/bunsen-netinstall#3]
Not exactly an issue, but

https://github.com/BunsenLabs/bunsen-netinstall/blob/master/install

I understand that this is a demo vehicle, but would it be wasteful to name exactly which system files will be replaced/modified? Since the script is quite gigantic (a note in the install header will do just fine).

**Comment by johnraff** [comment]
There are not all that many system files installed by this version of the script. Look in the folders sysfiles1 and sysfiles2 to see what will go in.

After running the script you can also check ~/.bunsen-netinstall-logs/install.log for messages, but if all went well there should be lists of system files added and replaced in sysfiles-added and sysfiles-replaced in the same directory.

The long-term goal is for the script itself to do as little as possible, putting everything in the .deb files, so over time those files, and postinstall-commands, should reduce.

**Comment by johnraff** [comment]
Of course, the .deb packages themselves install a lot of system files! One or two are replaced also, eg /etc/skel/.profile and /etc/lightdm/lightdm.conf. At the moment, bunsen-configs is the only package that actually replaces existing system files.
