### ISSUE TITLE
need more hints for netinstall

### ISSUE THREAD

**Issue by Zeitvertreib** [BunsenLabs/bunsen-netinstall#4]
Hey,

did a netinstall of debian 8..
Question: is it sufficiant to do a netinstall w/o internet connection?
(because that is what i tried, got the following issue)

run your netinstall script, got the error, that rsync could not be installed. (script aborted)

(sound like no internet connection? well, i had it pugged at that time.)

**Comment by johnraff** [comment]
An internet connection is needed both for the Debian netinstall and to run this script afterwards. Everything is pulled down from the net.

**Comment by Sector11** [comment]
`i had it pugged at that time`
wired or wifi?

**Comment by Zeitvertreib** [comment]
Thanks for response and for the hint, that Debian's netinstall has to be done with network up in order to run the bunsen-netinstall script! (Because installgin Debian's netinstall is possible to do without an internet connection. very minimalistic, but possible and very dead simple to do. And it would be nice, if the bunsen netinstall would work on the minimal set up. ..I read it's 'testing only' I don't complain, but don't want to miss the opportunity to mention^^)

However I'll give it another try on monday. (in 3 days I close this issue or reproduce)

And with 'pugged' (sry for the typo) -> plugged, I ment wired.

**Comment by Zeitvertreib** [comment]
Ok,

second try, works! nice :)

I probably didn't configure my ip/dhcp properly..

However, installation took a while, so trying to reproduce might has to wait.
Also some meta-bunsen packages could not be authenticated. But I expect this for alpha/beta state (?).

I would suggest to add a 3) to the debian netinstall hint. somthing like:
If you netinstall w/o internet connection, be sure to set it up afterwards, but before you run the install script.

Meanwhile it looks neat :)

**Comment by johnraff** [comment]
_None_ of the bunsen packages can be authenticated because they don't come from a Debian repository with signatures. They're built by the install script and installed from a local repository (/var/local/debs) created on your own computer.

**Comment by bguerin** [comment]
> None of the bunsen packages can be authenticated because they don't come from a Debian repository with signatures. They're built by the install script and installed from a local repository (/var/local/debs) created on your own computer.

I think one can use Travis CI to build debs and automatically upload them to a deb signed repository, hosted via GitHub pages.
It is a bit painful to set up because of the private key, which must be splitted into several secured variables, but it works !
See : https://github.com/bguerin/bguerin.github.io

I would love to help with this, but I do not have much free time these days ... but if someone would like to start, feel free to ask me questions !
