### ISSUE TITLE
Problem installing local .deb files

### ISSUE THREAD

**Issue by smacz42** [BunsenLabs/bunsen-netinstall#5]
This error occurred while installing on a HP Pavilion i386:

```
~/.bunsen-netinstall-logs/install.log

The following package was automatically installed and is no longer required:
  config-package-dev
Use 'apt-get autoremove' to remove it.
The following extra packages will be installed:
  libglew1.10 lua-bitop lua-expat lua-filesystem lua-penlight lua-posix
  lua-socket lua5.2 mesa-utils python-ecdsa python-paramiko
Suggested packages:
  glew-utils
 The following NEW packages will be installed:
  bunsen-common bunsen-configs bunsen-conky bunsen-docs
  bunsen-faenza-icon-theme bunsen-images bunsen-pipemenus bunsen-themes
  bunsen-utilities bunsen-welcome libglew1.10 lua-bitop lua-expat
   lua-filesystem lua-penlight lua-posix lua-socket lua5.2 mesa-utils
  python-ecdsa python-paramiko
0 upgraded, 21 newly installed, 0 to remove and 0 not upgraded.
Need to get 633 kB/88.6 MB of archives.
After this operation, 159 MB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
######## WARNING ########
apt-get returned an error installing bunsen packages
----------------------------------------------------------

There was a problem installing the local .deb files.
There may be some information in /home/smacz/.bunsen-netinstall-logs/install.log.
Would you like to continue anyway, or exit?
(press enter to continue, any other key to exit)
```

I continued the install (as this was my second time recieving that error). After it was done I ran:

```
$ sudo apt-get autoremove
```

My first attempt to install them by listing them in a text file and piping them always spit out that unhelful "Abort" message with an explanation same as right above the "------" separator in the `install.log` file without waiting for a "[Y|n]" response:

```
$ cat packages.txt | xargs sudo apt-get install
```

I vaguely remember attempting to pass `--force-yes` and/or `-y` flag/switch to apt-get without success to the above.

The named packages installed just fine one-by-one, each prompting me asking if I wanted to continue even though it wasn't...verifiable(?). BunsenLabs is now up and running on this partition.

I have yet to do the Broadcom b43-installer dance to get wifi working, but I didn't figure that had anything to do with the error I recieved. Ethernet worked just fine for the install.

I've netinstalled base debian and ran this script twice with the same results. I would be more than happy to attempt a third time to gather data. I was unable to find anything telling in `/var/log/apt/*` or `/var/log/dpkg.log`.

**Comment by johnraff** [comment]
`Do you want to continue? [Y/n] Abort.` 
This sounds as if you rejected the prompt. Did you press Y before Enter?

**Comment by smacz42** [comment]
No button was pressed before the `Abort` and then the `###WARNING###` appeared. There was no hesitation. It did not wait for my input before signaling an abort.

**Comment by johnraff** [comment]
That's very strange. At that point you're under the control of apt-get. The WARNING comes from the script based on what apt-get returns.

I've not heard of such an issue before, but I'll run the script again to see if some weird bug has crept in.

And thank you for the bug report.

**Comment by smacz42** [comment]
I had just ran it in a VM last week and nothing of the sort had happened. This is the first time doing it on physical hardware. I'm going to do a reinstall tonight. I was thinking about before running the script putting some debug statements around that part of the install. Did you have any suggestions where they would go or what to put?

**Comment by smacz42** [comment]
I'm going to try some statements in the `github_install` script right after it `cd "$scriptdir"`. And also instead of going to `warnlog` on fail trying to `apt-get -f install` or `apt-get --force-yes install`. I have a sneaking suspicion (more of a hunch, really) that it's getting hung up on the non-verifiable aspect of those packages. (Why it would is beyond me though)

**Comment by johnraff** [comment]
Also, why would no-one else have reported such problems?

**Comment by smacz42** [comment]
That's what I thought as well. But it turns out that I needed to pass the `--force-yes` flag to `apt` for it to even get me to the prompt.

[Pastebin proof](http://pastebin.com/6VkmVxSe) (TTL=1 Week)

In there I included the function that I created to troubleshoot the issue and the log file showing what had occurred and the necessary steps to force the install.

I...don't know what more to say. Trust me, it's as baffling on my end as I could imagine it would be on yours @johnraff.

**Comment by johnraff** [comment]
It's weird. I think the "problem" apt referred to with --assume-yes was that the "The following packages cannot be authenticated!" It needs a Y from you.
 --assume-yes only works if there are no prompts needed.
However, on the first "straight" run it aborts just after the prompt before that - when it's just asking if you want to continue with the upgrade. I guess --assume-yes is getting you through that one. 

I don't suppose it's a problem with the keyboard??

**Comment by smacz42** [comment]
Haha I thought of that too! But I would assume that I'd be seeing an army of "n"s scrolling across the screen were that to be the case.

I'm going to attempt to duplicate this on one of my other machines. This one seems like such a special little snowflake.

**Comment by smacz42** [comment]
I'm going to close this issue as it is not reproducible on any other machine, and has not been reported anywhere else. I've just installed it on two other machines and there was no such hangup. It prompted me to install the packages without verification just as it should.

I'll just chalk it up to a ghost of Windoze in this second hand laptop.

**Comment by johnraff** [comment]
Let's keep our eyes open for anything else like it.

**Comment by smacz42** [comment]
Will do.
