### ISSUE TITLE
File "extra_repos" doesn't exist anymore but is mentioned in README and ./install

### ISSUE THREAD

**Issue by UrsMetz** [BunsenLabs/bunsen-netinstall#6]
I've just had a look at the ./install script and noticed a reference to "extra_repos" but couldn't find anything like that in the current HEAD. `git log --name-status` showed that the file `extra_repos` was removed in commit 9e7a282 .Yet it is still listed in README.

**Comment by johnraff** [comment]
Hi @UrsMetz thank you for your report. The install script is a generic one which is also used in other installers in almost the same form, so the section of code which looks for extra_repos remains. If the file is not present it moves on. I will remove extra_repos from this README though.
