### ISSUE TITLE
Add at-spi2-core to base install to fix gtk3 programs warnings

### ISSUE THREAD

**Issue by aponad** [BunsenLabs/bunsen-netinstall#7]
Launching any gkt3 program (meld, gnome-disks) will result in terminal warning (this is especially irritating in meld then you are merging a lot of files which result in tons of warnings)

```
** (meld:11327): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
```

```
** (gnome-disks:11638): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
```

Installing `at-spi2-core` fixes the problem.

**Comment by johnraff** [comment]
Confirmed at-spi2-core install fixes the org.a11y.Bus warnings.
It's a small package, so I've provisionally added it to the install list in the netinstall script.

@wonderfulll thank you for catching this.
